[general]
galaxy_types=LRG
regions=all,north,south,des,south+des

zbins_LRG=0.4,1.1
weights_LRG=weight_imlin_fkp
use_fnl_weights_LRG=True
use_zcmb=True

full_lss_path=/global/cfs/projectdirs/desi/survey/catalogs/DA2/LSS/loa-v1/LSScats/
lensing_path=/global/cfs/projectdirs/desi/survey/catalogs/DA2/LSS/loa-v1/LSScats/nonKP/
version=v2
apply_cut_secondary_properties=True
apply_individual_cuts=True
do_full_alpha_stepwise_calculation=True
dkappa = 0.002
dkappa_max = 0.03

fiber_mag_lensing = Tabulated
#alternatives:
#deVaucouleurs_prifle
#Exponential_profile
#Tabulated
#no_correction

[secondary_properties]
Xval_LRG=FIBERFLUX_Z
relevant_secondary_properties_LRG=DELTACHI2

[individual_cuts]
validate_individual_cuts=False

[output]
output_path=/global/cfs/cdirs/desi/users/schiarenza/magnification_bias_DESI/measurements/
output_filename=DESI_magnification_bias_LRG.h5
