[general]
galaxy_types=QSO
regions=all,north,south,des,south+des

zbins_QSO=0.8,1.6,2.1
weights_QSO=weight_FKP
use_zcmb=True

full_lss_path=/global/cfs/projectdirs/desi/survey/catalogs/DA2/LSS/loa-v1/LSScats/
lensing_path=/global/cfs/projectdirs/desi/survey/catalogs/DA2/LSS/loa-v1/LSScats/nonKP/
version=v2
apply_cut_secondary_properties=True
apply_individual_cuts=True
do_full_alpha_stepwise_calculation=True
dkappa = 0.002
dkappa_max = 0.03

fiber_mag_lensing = Tabulated
#alternatives:
#deVaucouleurs_prifle
#Exponential_profile
#Tabulated
#no_correction

; QSO has no secondary cuts -- no [secondary_properties] entry needed

[individual_cuts]
validate_individual_cuts=False

[output]
output_path=/global/cfs/cdirs/desi/users/schiarenza/magnification_bias_DESI/measurements/
output_filename=DESI_magnification_bias_QSO_c3cmb.h5
