[general]
galaxy_types=ELG_LOPnotqso
regions=all,north,south,des,south+des

zbins_ELG_LOPnotqso=1.1,1.6
weights_ELG_LOPnotqso=weight_FKP
use_zcmb=True

full_lss_path=/global/cfs/projectdirs/desi/survey/catalogs/DA2/LSS/loa-v1/LSScats/
lensing_path=/global/cfs/projectdirs/desi/survey/catalogs/DA2/LSS/loa-v1/LSScats/nonKP/
version=v2
apply_cut_secondary_properties=True
apply_individual_cuts=True
do_full_alpha_stepwise_calculation=True
dkappa = 0.002
dkappa_max = 0.03

fiber_mag_lensing = Tabulated
#alternatives:
#deVaucouleurs_prifle
#Exponential_profile
#Tabulated
#no_correction

[secondary_properties]
Xval_ELG_LOPnotqso=FIBERFLUX_G
relevant_secondary_properties_ELG_LOPnotqso=o2c

[individual_cuts]
validate_individual_cuts=False

[output]
output_path=/global/cfs/cdirs/desi/users/schiarenza/magnification_bias_DESI/measurements/
output_filename=DESI_magnification_bias_ELG.h5
